### ISSUE TITLE
Settings Database

### ISSUE THREAD

**Issue by oisian** [tankerkiller125/MC-Donations#18]
Howdy, it would seem you are getting all the settings from the database but you have not included it with the install??

**Comment by tankerkiller125** [comment]
Correct The software is still under heavy develpment so as per such I have
not yet exported a default DB and included the file

**Comment by tankerkiller125** [comment]
Not to mention that in the future I would like to include an easy GUI based install sometime before the first main release

**Comment by oisian** [comment]
Mind including it? I'd like to take a look, not to worry if you don't want to

**Comment by tankerkiller125** [comment]
A Gist can be found here https://gist.github.com/tankerkiller125/52db0c95f8ef7558760a (note not all settings are in it yet)

**Comment by tankerkiller125** [comment]
A better one can now be found [here](https://github.com/TrackingTeam/Issue-Track/blob/develop/application/config/settings.sql)
